<a href="https://colab.research.google.com/github/taka-sigure/AI_Datascience_Intern/blob/main/test_syoumatsu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import pandas_profiling as pdp
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
df_train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cancer_train.csv')
df_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cancer_test.csv')

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                199 non-null    object 
 1   radius_mean              199 non-null    float64
 2   texture_mean             199 non-null    float64
 3   perimeter_mean           199 non-null    float64
 4   area_mean                199 non-null    float64
 5   smoothness_mean          199 non-null    float64
 6   compactness_mean         199 non-null    float64
 7   concavity_mean           199 non-null    float64
 8   concave points_mean      199 non-null    float64
 9   symmetry_mean            199 non-null    float64
 10  fractal_dimension_mean   199 non-null    float64
 11  radius_se                199 non-null    float64
 12  texture_se               199 non-null    float64
 13  perimeter_se             199 non-null    float64
 14  area_se                  1

In [ ]:
diagnosis_mapping = {'M':1, 'B':0}
df_train['diagnosis'] = df_train['diagnosis'].map(diagnosis_mapping)

In [ ]:
x = df_train.drop('diagnosis', axis=1).values
t = df_train['diagnosis'].values
x_test =df_test.values

In [ ]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

In [ ]:
std_scaler.fit(x)

StandardScaler()

In [ ]:
# 標準化
x_train_std = std_scaler.transform(x)

In [ ]:
x_train_std

array([[ 1.83548541, -0.39562862,  1.68833996, ...,  1.12857372,
        -0.17482226,  0.33365333],
       [ 0.29902089, -1.40966441,  0.23149948, ..., -0.493151  ,
        -0.60956867, -0.93873321],
       [-0.49777019, -0.41564248, -0.43720064, ..., -0.61888057,
        -0.49550972,  0.6058821 ],
       ...,
       [-0.13792905, -0.09319689, -0.10698346, ...,  0.42367898,
        -0.18474043,  0.29612508],
       [-0.10651435, -1.39632183, -0.16484379, ..., -0.86287062,
        -0.05415121, -0.92205398],
       [ 0.87305317,  1.10541121,  0.91549125, ...,  1.18926002,
         0.75583258,  3.00709472]])

In [ ]:
# モデルの定義
from sklearn.svm import SVC
svc_std = SVC()

In [ ]:
svc_std.fit(x_train_std, t)

SVC()

In [ ]:
print('train score scaling : ', svc_std.score(x_train_std, t))

train score scaling :  0.9798994974874372


In [ ]:
np.unique(t, return_counts=True)

(array([0, 1]), array([125,  74]))

In [ ]:
std_scaler.fit(x_test)
x_test_std = std_scaler.transform(x_test)
x_test_std

array([[-0.76683516,  0.47971832, -0.7742543 , ..., -0.43429692,
        -0.16647855,  0.2051906 ],
       [-1.77890253,  1.46034556, -1.76168716, ..., -1.6208093 ,
         0.20711647,  0.76897997],
       [-1.17715547,  0.04852053, -1.11804215, ..., -0.22345375,
        -0.50418235,  0.03085428],
       ...,
       [ 0.77466873,  0.06243013,  0.67344318, ..., -0.41165027,
        -0.65916719, -1.25270957],
       [-0.99946211,  0.23166368, -0.92901928, ..., -0.74131667,
        -0.89409157,  0.30408313],
       [-0.71918867,  1.0986958 , -0.6920354 , ..., -0.23721374,
        -1.3362062 ,  0.15421507]])

In [ ]:
y = svc_std.predict(x_test_std)
y

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0])

In [ ]:
 pd.Series(y, name='pred').to_csv('submission.csv', index=None, line_terminator='\n')